# Generated by Django 3.1 on 2020-08-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('roll_number', models.IntegerField()),
                ('branch', models.CharField(choices=[('CSE', 'COMPUTER'), ('ECE', 'ELECTRONIC'), ('ME', 'MECHANICAL'), ('CE', 'CIVIL'), ('IT', 'IT')], default='CSE', max_length=3)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
