# Generated by Django 3.1 on 2020-08-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attendence',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
