# Generated by Django 3.1 on 2020-08-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_student_attendence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='attendence',
            field=models.IntegerField(default=0),
        ),
    ]
